name = "worker"
main = "worker/index.ts"
compatibility_date = "2023-10-25"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "intan-prod"
database_id = "3b084fca-06a4-4149-9a30-be707a77b3ff"
